### ISSUE TITLE
UCloud for Teaching Working Group

### ISSUE THREAD

**Issue by emolinaro** [SDU-eScience/UCloud-Courses#1]
# Repository Setup

This epic tracks the initial configuration of the repository.

## Technical settings
- [x] Define requirements to use this repository
- [x] Develop scripts to set up a new course
- [x] Define a list of base images to be used to build a course
- [ ] ~Add minimal linting configuration~
- [x] Add an example of a course already deployed on UCloud (e.g. the Genomics Sandbox)

## Usage settings 
Create a dedicated wiki page to discuss the following points:
- [x] A set of requirements to request a new course on UCloud
- [x] Draft for the teacher agreement
- [x] The financial model

**Comment by FedericaLoVerso** [comment]
We are finalizing the financial model and planning webinar/workshop for the end of April if possible.

**Comment by emolinaro** [comment]
All tasks are completed.
